//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Usuaris
{
    public int id_usuari { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> data_naixement { get; set; }
    public string sexe { get; set; }
}
